ssk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = ([
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
]

    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

)

admin.site.site_header = "SSK TRADING W.L.L Administration"
admin.site.site_title = " SSK TRADING W.L.L Admin Portal"
admin.site.index_title = "Welcome to  SSK TRADING W.L.L Admin Portal"

web/urls.py
from django.urls import path

from . import views


app_name = "web"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("products/", views.ProductListView.as_view(), name="products"),
    path("updates/", views.UpdatesView.as_view(), name="update"),
    path("update/<str:slug>/", views.UpadateDetailView.as_view(), name="update_detail"),
    path("contact/", views.ContactView.as_view(), name="contact"),
]

web/models.py
from django.db import models
from django.urls import reverse_lazy
from tinymce.models import HTMLField

# Create your models here.

class Category(models.Model):
  name = models.CharField(max_length=255) 
  image = models.ImageField(upload_to='media')
  
  def __str__(self):
      return self.name
  
  
class Product(models.Model):
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  name = models.CharField(max_length=255)
  image = models.ImageField(upload_to='media')
  description = models.TextField(null=True,blank=True)
  
  def __str__(self):
      return self.name
  
    

class Testimonial(models.Model):
  image = models.ImageField(upload_to='media',null=True,blank=True)
  name = models.CharField(max_length=255)
  designation = models.CharField(max_length=255,null=True,blank=True)
  description = models.TextField()
  
  
  def __str__(self):
      return self.name
  
  
class Updates(models.Model):
    image = models.ImageField(upload_to = "event")
    date  = models.DateField(blank=True,null=True)
    title = models.CharField(max_length=100)
    slug= models.SlugField()
    description = HTMLField()
    
    
    def get_absolute_url(self):
        return reverse_lazy("web:update_detail", kwargs={"slug": self.slug})
    
    class Meta:
        verbose_name = ('Update')
        verbose_name_plural = ('Updates')

    def __str__(self):
        return self.title
      
      
      
  
class ClientLogo(models.Model):
    image = models.ImageField(upload_to="media")
    
    def __str__(self):
        return str(self.image)
      
      

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()
    
    def __str__(self):
        return self.name
      
  
class ProductEnquiry(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=50)
    email= models.EmailField(null=True,blank=True)
    message = models.TextField()
    
    
    class Meta:
        verbose_name = ('Product Enquiry')
        verbose_name_plural = ('Product Enquiries')

    def __str__(self):
        return self.name
      
  
class Organization(models.Model):
    image = models.ImageField(upload_to="media",null=True,blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)
    
    def __str__(self):
        return self.name

web/forms.py
from django import forms
from .models import Contact,ProductEnquiry


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
        
class ProductEnquiryForm(forms.ModelForm):
    class Meta:
        model = ProductEnquiry
        fields = "__all__"

web/views.py
from django.shortcuts import render

from django.http import JsonResponse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormView

from .models import Product,Category,Testimonial,Updates,ClientLogo,Organization
from .forms import ContactForm,ProductEnquiryForm

# Create your views here.

class IndexView(TemplateView):
    template_name = 'web/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["testimonials"] = Testimonial.objects.all()
        context["updates"] = Updates.objects.all()[:3]
        context["clients"] = ClientLogo.objects.all()  
        context["organizations"] = Organization.objects.all()
        context["is_index"] = True
        return context
    
    
class AboutView(TemplateView):
    template_name = 'web/about.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["clients"] =  ClientLogo.objects.all()
        context["categories"] = Category.objects.all() 
        
        return context
    
    
class ContactView(FormView):
    form_class = ContactForm
    template_name = "web/contact.html"

    def form_valid(self, form):
        form.save()

        response_data = { "status": "true","title": "Thankyou for your quirey submitted","message": "our team will revert to you at the earliest ",}
        return JsonResponse(response_data)

    def form_invalid(self, form):
        response_data = {"status": "false","title": "Form validation error",}
        return JsonResponse(response_data, status=400)
    

class UpdatesView(ListView):
    model = Updates
    template_name = 'web/updates.html'
    
class UpadateDetailView(DetailView):
    model = Updates
    template_name = 'web/update_detail.html'
    
    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        current_update = self.get_object()
        context["updates"] = Updates.objects.exclude(pk=current_update.pk).order_by("-id")
        return context
    
    
    
class ProductListView(ListView,FormView):
    model = Product
    form_class = ProductEnquiryForm
    template_name = "web/product.html"
    paginate_by=20
    
    def get_queryset(self):
        category = self.request.GET.get("category")
        products = super().get_queryset()  # Retrieve the base queryset
        
        if category:
            products = products.filter(category__id=category)
            
        return products
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all() 
        return context
    
    
    def form_valid(self, form):
        form.save()
        response_data = { "status": "true","title": "Successfully submitted","message": "our team will revert to you at the earliest ",}
        return JsonResponse(response_data)

    def form_invalid(self, form):
        response_data = {"status": "false","title": "Form validation error",}
        return JsonResponse(response_data, status=400)
    
    

templates/web/backup.html
faq


<section class="faq__area-two section-py-120">
    <div class="container">
        <div class="row my-auto">
            <div class="col-lg-8">
                <div class="faq__content">
                    <div class="section__title section__title-three mb-40">
                        <span class="sub-title">More About Us</span>
                        <h2 class="title">Frequently Asked Questions</h2>
                    </div>
                    <div class="faq__wrap-two">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        01. What does SSK Trading W.I.I. specialize in?
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="">
                                    <div class="accordion-body">
                                        <p>SSK Trading W.I.I. specializes in the supply of construction materials such as PPE (Personal Protective Equipment), hardware, tools, and consumables.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        02. How long has SSK Trading W.I.I. been operating in the Qatar market?
                                    </button>
                                </h2>
                                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="">
                                    <div class="accordion-body">
                                       <p>SSK Trading W.I.I. has been a leading name in the Qatar market for over a decade.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                        03. What types of projects does SSK Trading W.I.I. supply products to?
                                    </button>
                                </h2>
                                <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="">
                                    <div class="accordion-body">
                                        <p>SSK Trading W.I.I. supplies products to various mega projects running in Qatar, catering to both government and private infrastructure developers and contractors.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                        04. Are SSK Trading W.I.I.'s products approved by regulatory bodies?
                                    </button>
                                </h2>
                                <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="">
                                    <div class="accordion-body">
                                        <p>Yes, the products supplied by SSK Trading W.I.I. are approved by most renowned consultants working in Qatar.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                        05. What is the capacity of SSK Trading W.I.I.'s warehouse?
                                    </button>
                                </h2>
                                <div id="collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <p>SSK Trading W.I.I. maintains a 2000 square meters warehouse, ensuring the ideal stock of goods for continuous supply.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                        06. From which countries does SSK Trading W.I.I. import its products?
                                    </button>
                                </h2>
                                <div id="collapseSix" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <p>SSK Trading W.I.I. imports products from various countries, including China, India, and Pakistan.</p>    
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-none d-lg-block col-lg-4 m-auto">
                <div class="faq__sidebar my-auto">
                   
                    <div class="sidebar__discount">
                        <div class="sidebar__logo">
                            <a href="/"><img src="{% static 'web/img/ext/logo.svg' %}" alt="logo"></a>
                        </div>
                        <h2 class="title">Need Help? We Are Here <br> To Help You</h2>
                        <div class="sidebar__content">
                            <h4 class="title-two mb-4">Get In Touch</h4>
                            <a href="{% url 'web:contact' %}" class="btn btn-two">Get A Quote</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/web/partials/footer.html
{% load static %}

  <!-- footer-area -->
  <footer class="footer__area">
    <div class="container">
       
        <div class="footer__top">
            <div class="row">
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-8">
                    <div class="footer__widget">
                        <div class="footer__logo">
                            <a href="/"><img src="{% static 'web/img/logo.svg' %}" alt="logo"></a>
                        </div>
                        <div class="footer__content">
                            <p>Style meets safety, excellence meets reliability - Experience the Fashion Center difference today</p>
                        </div>
                        <div class="footer__social">
                            <ul class="list-wrap">
                                <li><a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="https://twitter.com/home" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                                <li><a href="https://www.instagram.com/" target="_blank"><i class="fab fa-youtube"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-6 col-xl-2 col-lg-4 col-md-3 col-sm-4">
                    <div class="footer__widget">
                        <h4 class="footer__widget-title">Useful Links</h4>
                        <div class="footer__widget-link">
                            <ul class="list-wrap">
                                <li>
                                    <a href="/"><i class="renova-right-arrow"></i><span>Home</span></a>
                                </li>
                                <li>
                                    <a href="{% url "web:about" %}"><i class="renova-right-arrow"></i><span>About Us</span></a>
                                </li>
                                <li>
                                    <a href="{% url "web:products" %}"><i class="renova-right-arrow"></i><span>Products</span></a>
                                </li>
                                <li>
                                    <a href="{% url "web:update" %}"><i class="renova-right-arrow"></i><span>Updates</span></a>
                                </li>
                                <li>
                                    <a href="{% url "web:contact" %}"><i class="renova-right-arrow"></i><span>Contact</span></a>
                                </li>
                               
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-6 col-xl-2 col-lg-4 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h4 class="footer__widget-title">Our PRODUCTS</h4>
                        <div class="footer__widget-link">
                            <ul class="list-wrap">
                                {% for i in all_categories|slice:":5" %}
                                <li>
                                    <a href="{% url 'web:products' %}?category={{ i.id }}"><i class="renova-right-arrow"></i><span>{{i.name}}</span></a>
                                </li>
                                {% endfor %}
                               
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-4 col-sm-6">
                    <div class="footer__widget">
                        <h4 class="footer__widget-title">CONTACT</h4>
                        <div class="footer__widget-link">
                            <ul class="list-wrap">
                                <li>
                                    <a href="tel:+97470974683"><i class="renova-right-arrow"></i><span>+974 7097 4683</span></a>
                                </li>
                                <li>
                                    <a href="mailto:sales@safetyproductsqatar.com"><i class="renova-right-arrow"></i><span>sales@safetyproductsqatar.com</span></a>
                                </li>
                                <li>
                                    <a href="mailto:accounts@safetyproductsqatar.com"><i class="renova-right-arrow"></i><span>accounts@safetyproductsqatar.com</span></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><i class="renova-right-arrow"></i><span>Fashion Center Uniform, Tumama, Furjan Market 33 C.R. No: 121842, P.O. Box: 9044, Doha - Qatar</span></a>
                                </li>
                               
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="footer__bottom">
            <div class="row align-items-center">
                <div class="col-md-7">
                    <div class="copyright-text">
                        <p>© 2024 Gedexo. All Rights Reserved</p>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
</footer>
<!-- footer-area-end -->

templates/web/partials/header.html
  {% load static %}


    <!-- header-area -->
    <header>
        <div class="tg-header__top">
            <div class="container custom-container">
                <div class="row align-items-center">
                    {% comment %} <div class="col-lg-3">
                        <div class="tg-header__top-menu">
                            <ul class="list-wrap">
                                <li><a href="contact.html">Contact</a></li>
                                <li><a href="contact.html">Careers</a></li>
                                <li><a href="contact.html">Insights</a></li>
                            </ul>
                        </div>
                    </div> {% endcomment %}
                    <div class="col-lg-8 text-start">
                        <div class="tg-header__top-delivery">
                            <p class="text-start">
                                Fashion Center Uniform, Tumama, Furjan Market 33 C.R. No: 121842, P.O. Box: 9044, Doha - Qatar</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="tg-header__top-social">
                            <ul class="list-wrap">
                                <li><a href="https://www.facebook.com/" target="_blank">FB</a></li>
                                <li><a href="https://twitter.com/home" target="_blank">TW</a></li>
                                <li><a href="https://www.linkedin.com/" target="_blank">LI</a></li>
                                <li><a href="https://www.instagram.com/" target="_blank">IN</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="header-fixed-height"></div>
        <div id="sticky-header" class="tg-header__area">
            <div class="container custom-container">
                <div class="row">
                    <div class="col-12">
                        <div class="tgmenu__wrap">
                            <nav class="tgmenu__nav">
                                <div class="offCanvas-toggle">
                                    <a href="javascript:void(0)" class="menu-tigger">
                                        <img src="{% static 'web/img/icons/bar_icon.svg' %}" alt="" class="injectable">
                                    </a>
                                </div>
                                <div class="logo">
                                    <a href="/"><img src="{% static 'web/img/logo.svg' %}" alt="Logo"></a>
                                </div>
                                <div class="tgmenu__navbar-wrap tgmenu__main-menu d-none d-xl-flex">
                                    <ul class="navigation">
                                        <li class=" "><a href="/">Home</a></li>
                                        <li class=""><a href="{% url 'web:about' %}">About</a></li>
                                        <li class=""><a href="{% url 'web:products' %}">Products</a></li>
                                        <li class=""><a href="{% url 'web:update' %}">Updates</a></li>
                                        <li class=""><a href="{% url 'web:contact' %}">Contact</a></li>
                                       
                                    </ul>
                                </div>
                                <div class="tgmenu__action">
                                    <ul class="list-wrap">
                                       
                                        <li class="header-btn">
                                            <a href="{% url 'web:contact' %}" class="btn border-btn">Get In Touch</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="mobile-nav-toggler"><i class="tg-flaticon-menu-1"></i></div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Mobile Menu  -->
        <div class="tgmobile__menu">
            <nav class="tgmobile__menu-box">
                <div class="close-btn"><i class="tg-flaticon-close-1"></i></div>
                <div class="nav-logo">
                    <a href="/"><img src="{% static 'web/img/logo1.svg' %}" alt="Logo"></a>
                </div>
               
                <div class="tgmobile__menu-outer">
                    <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
                </div>
                <div class="social-links">
                    <ul class="list-wrap">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="tgmobile__menu-backdrop"></div>
        <!-- End Mobile Menu -->

        <!-- header-search -->
        <div class="search__popup">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="search__wrapper">
                            <div class="search__close">
                                <button type="button" class="search-close-btn">
                                    <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path d="M17 1L1 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                            stroke-linejoin="round"></path>
                                        <path d="M1 1L17 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                            stroke-linejoin="round"></path>
                                    </svg>
                                </button>
                            </div>
                            <div class="search__form">
                                <form action="#">
                                    <div class="search__input">
                                        <input class="search-input-field" type="text" placeholder="Type keywords here">
                                        <span class="search-focus-border"></span>
                                        <button>
                                            <svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                                                xmlns="http://www.w3.org/2000/svg">
                                                <path d="M9.55 18.1C14.272 18.1 18.1 14.272 18.1 9.55C18.1 4.82797 14.272 1 9.55 1C4.82797 1 1 4.82797 1 9.55C1 14.272 4.82797 18.1 9.55 18.1Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                <path d="M19.0002 19.0002L17.2002 17.2002" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                            </svg>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="search-popup-overlay"></div>
        <!-- header-search-end -->

        <!-- offCanvas-menu -->
        <div class="offCanvas__info">
            <div class="offCanvas__close-icon menu-close">
                <button><i class="far fa-window-close"></i></button>
            </div>
            <div class="offCanvas__logo mb-30">
                <a href="/"><img src="{% static 'web/img/logo1.svg' %}" alt="Logo"></a>
            </div>
            <div class="offCanvas__side-info mb-30">
                <div class="contact-list mb-30">
                    <h4>Office Address</h4>
                    <p>Fashion Center Uniform, Tumama, <br> Furjan Market 33 C.R. No: 121842, P.O. Box: 9044, Doha - Qatar</p>
                </div>
                <div class="contact-list mb-30">
                    <h4>Phone Number</h4>
                    <p>+974 7097 4683</p>
                </div>
                <div class="contact-list mb-30">
                    <h4>Email Address</h4>
                    <p>sales@safetyproductsqatar.com</p>
                    <p>accounts@safetyproductsqatar.com</p>
                </div>
            </div>
            <div class="offCanvas__social-icon mt-30">
                <a href="javascript:void(0)"><i class="fab fa-facebook-f"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-twitter"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-google-plus-g"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <div class="offCanvas__overly"></div>
        <!-- offCanvas-menu-end -->

    </header>
    <!-- header-area-end -->

templates/web/updates.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}




    <!-- main-area -->
    <main class="main-area fix">

       
        <!-- blog-post-area -->
        <section class="blog__post-area-two section-pt-120 section-pb-90">
            <div class="container">
                <div class="row justify-content-center gutter-24">
                    {% for item in object_list %}
                    <div class="col-lg-4 col-md-6">
                        <div class="blog__post-item shine__animate-item">
                            <div class="blog__post-thumb">
                                <a href="{{item.get_absolute_url}}" class="shine__animate-link">
                                    <img src="{{item.image.url}}" alt="img">
                                </a>
                            </div>
                            <div class="blog__post-content">
                                <div class="blog__post-meta">
                                    <ul class="list-wrap">
                                       
                                        <li>{{item.date}}</li>
                                    </ul>
                                </div>
                                <h4 class="title"><a href="{{item.get_absolute_url}}">{{item.title}}</a></h4>
                                <a href="{{item.get_absolute_url}}" class="btn">Read Details</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                   
                </div>
            </div>
        </section>
        <!-- blog-post-area-end -->

    

    </main>
    <!-- main-area-end -->

{% endblock %}